<robot name="mycar"  xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 摄像头部件 -->
    <!-- 1.参数 -->
    <!-- 
        参数:
            连杆属性:厚度\宽度\高度
            关节属性:xyz
     -->

    <xacro:property name="camera_length" value="0.02"/> <!-- 厚度x-->
    <xacro:property name="camera_width" value="0.05"/> <!-- 厚度y-->
    <xacro:property name="camera_height" value="0.05"/> <!-- 高度z-->
    <xacro:property name="camera_mass" value="0.01"/> <!-- 质量-->


    <xacro:property name="joint_camera_x" value="0.08"/>
    <xacro:property name="joint_camera_y" value="0"/>
    <xacro:property name="joint_camera_z" value="${base_length /2 + camera_height/2}"/>
     <!-- 2.设计link和joint -->
     <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
     </link>
     <gazebo reference="camera">
        <material>Gazebo/Blue</material>

     </gazebo>

     <joint name="camera2base" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0"/>
     </joint>

</robot>